# Generated by Django 4.0 on 2022-03-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='rent',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
